version: "3"
services:
  ya_test:
    tty: true
    build: .
    image: ya_test:latest
    environment:
      DATABASE_NAME: ya_test
      DATABASE_USER: ya_test
      DATABASE_PASSWORD: 123456
      DATABASE_HOST: db
      DEBUG: 1
    volumes:
      - app_static_files:/usr/src/app/ya_test/static:rw
      - app_media_files:/usr/src/app/ya_test/media:rw
      - .:/usr/src/app/
    networks:
      - db
    depends_on:
      - db
    command: gunicorn --config /gunicorn.conf --reload ya_test.wsgi:application

  db:
    tty: true
    image: postgres:11-alpine
    volumes:
      - postgres_db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ya_test
      POSTGRES_DB: ya_test
      POSTGRES_PASSWORD: 123456
    networks:
      - db
    ports:
      - 5432:5432

networks:
  db:


volumes:
  postgres_db: {}
  app_static_files: {}
  app_media_files: {}
