---

- name: Run Django database migrations
  django_manage:
    command: migrate
    app_path: "{{ django_project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  when: run_django_db_migrations is defined and run_django_db_migrations
  tags: django, migrate, deploy

- name: Run Django collectstatic
  django_manage:
    command: collectstatic
    app_path: "{{ django_project_path }}"
    virtualenv: "{{ virtualenv_path }}"
    settings: "{{ django_settings_file }}"
  environment: "{{ django_environment }}"
  when: run_django_collectstatic is defined and run_django_collectstatic
  tags: django, deploy, deploy-quick